### ISSUE TITLE
A lot of "never warmed up" warnings

### ISSUE THREAD

**Issue by brauliobo** [jruby/bench9000#3]
Is this the actual state or is there something wrong with my install?

```
~/P/o/bench9000 git:master ❯❯❯ ruby -Ilib bin/bench \
>   report --baseline 2.2.2 --notes doc/notes.html --data report.data \
>   jruby-9000-dev-truffle-graal all \
>   --show-commands
bash -c "JAVACMD=/home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//graalvm-jdk1.8.0/bin/java /home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//bin/jruby -J-Xmx2G -J-d64 -J-server -J-G:+TruffleCompilationExceptionsAreFatal -X+T -I/home/braulio/Projects/others/bench9000/lib/bench/..  /home/braulio/Projects/others/bench9000/lib/bench/benchmarks/classic/binary-trees.rb"
warning: jruby-9000-dev-truffle-graal classic-binary-trees never warmed up!
bash -c "JAVACMD=/home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//graalvm-jdk1.8.0/bin/java /home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//bin/jruby -J-Xmx2G -J-d64 -J-server -J-G:+TruffleCompilationExceptionsAreFatal -X+T -I/home/braulio/Projects/others/bench9000/lib/bench/..  /home/braulio/Projects/others/bench9000/lib/bench/benchmarks/classic/fannkuch-redux.rb"
bash -c "JAVACMD=/home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//graalvm-jdk1.8.0/bin/java /home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//bin/jruby -J-Xmx2G -J-d64 -J-server -J-G:+TruffleCompilationExceptionsAreFatal -X+T -I/home/braulio/Projects/others/bench9000/lib/bench/..  /home/braulio/Projects/others/bench9000/lib/bench/benchmarks/classic/mandelbrot.rb"
warning: jruby-9000-dev-truffle-graal classic-mandelbrot never warmed up!
bash -c "JAVACMD=/home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//graalvm-jdk1.8.0/bin/java /home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//bin/jruby -J-Xmx2G -J-d64 -J-server -J-G:+TruffleCompilationExceptionsAreFatal -X+T -I/home/braulio/Projects/others/bench9000/lib/bench/..  /home/braulio/Projects/others/bench9000/lib/bench/benchmarks/classic/n-body.rb"
warning: jruby-9000-dev-truffle-graal classic-n-body never warmed up!
bash -c "JAVACMD=/home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//graalvm-jdk1.8.0/bin/java /home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//bin/jruby -J-Xmx2G -J-d64 -J-server -J-G:+TruffleCompilationExceptionsAreFatal -X+T -I/home/braulio/Projects/others/bench9000/lib/bench/..  /home/braulio/Projects/others/bench9000/lib/bench/benchmarks/classic/pidigits.rb"
bash -c "JAVACMD=/home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//graalvm-jdk1.8.0/bin/java /home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//bin/jruby -J-Xmx2G -J-d64 -J-server -J-G:+TruffleCompilationExceptionsAreFatal -X+T -I/home/braulio/Projects/others/bench9000/lib/bench/..  /home/braulio/Projects/others/bench9000/lib/bench/benchmarks/classic/spectral-norm.rb"
warning: jruby-9000-dev-truffle-graal classic-spectral-norm never warmed up!
bash -c "JAVACMD=/home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//graalvm-jdk1.8.0/bin/java /home/braulio/.rbenv/versions/jruby-9.0.0.0+graal-dev//bin/jruby -J-Xmx2G -J-d64 -J-server -J-G:+TruffleCompilationExceptionsAreFatal -X+T -I/home/braulio/Projects/others/bench9000/lib/bench/..  /home/braulio/Projects/others/bench9000/lib/bench/benchmarks/classic/richards.rb"
```

**Comment by bjfish** [comment]
@brauliobo 
> The warning is ok to ignore here. It's just telling you that it has erred on the side of caution because it  didn't see the benchmark performance stabilise as much as it would have hoped 

From https://github.com/jruby/jruby/pull/2745#issuecomment-85060332

@chrisseaton I was confused by this message before too, maybe update this message?

**Comment by chrisseaton** [comment]
Yeah the problem is nobody knows a good way to automatically work out if a benchmark has warmed up. Some benchmarks may be modal as well, which further complicates things. We don't want to suggest that benchmarking is an exact science by hiding these problems.

What would be better to say? It's already a warning, not an error?

**Comment by brauliobo** [comment]
@chrisseaton I would only suggest to turn off these warning by default (and enabled with an option), as this is a issue to be known primarily by jruby truffle developers.
another thing worried me more: each test took a long time to run and some used 2gb of memory, which freezed my notebook with 8gb of ram

**Comment by bjfish** [comment]
@chrisseaton one idea, maybe the warning could be moved to the notes?

When I first saw the warning, I was under the impression that something was wrong with the command I had just run. However, this information may be data about the benchmarking and not the command being run.

Another idea, maybe it could look like this:
```
topaz-neural-net 4902.008372064519
took 85.107286s
warmed up false
```
Instead of this:
```
warning: jruby-9000-dev-truffle-graal topaz-neural-net never warmed up!
topaz-neural-net 4902.008372064519
took 85.107286s
```

**Comment by chrisseaton** [comment]
I'm not convinced enough to make this change myself, but I'd accept a PR if someone thinks it's important enough to do.

**Comment by brauliobo** [comment]
OFF @chrisseaton and @bjfish is it ok to decrease the maximum vm memory from 2gb to 1gb or less?

**Comment by chrisseaton** [comment]
Yes, but remember than MRI and Rubinius will (I think, never actually checked) take as much memory as they want from the system, so they may take much more than the 1 GB you allow JRuby. I believe it is not possible to say how much memory a program needs. If it has to run GC for every allocation does it have enough? Probably not, but it's still running. 2 GB is reasonable for these problems and the technology we're using.

**Comment by bjfish** [comment]
@chrisseaton Another suggestion for the "never warmed up" messages: an explanation could be added to the README.md Warmup section on what the warning means.

**Comment by chrisseaton** [comment]
Message added in 876f84872adf881cdb1ca4ea318572452d430165 and 30a1093b6988594d37862db36ff5c60ee7feefdc.
