### ISSUE TITLE
File organization

### ISSUE THREAD

**Issue by eregon** [jruby/bench9000#5]
Benchmarks are currently under lib/, which is fairly surprising (lib/ should be only bench9000's own code).
Should they be in `bench/` or `benchmarks/` for clarity instead?

What about bench dependencies, should we move them to vendor/?
Having them in a subdirectory of the benchmarks builds funny paths like:
`[bench9000/lib/bench]/benchmarks/chunky_png/chunky_png/lib/chunky_png`

**Comment by pitr-ch** [comment]
+1 for both moves

**Comment by chrisseaton** [comment]
Yes sounds good.
